name: test-build-deploy
run-name: Running feature branch workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: checkout_test
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: sudo /etc/init.d/mysql start
      - run: composer install
      - run: composer wp-install
      - run: vendor/phpunit/phpunit/phpunit

