name: test-build-deploy
run-name: Running feature branch workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: checkout_test
          MYSQL_HOST: 127.0.0.1
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3 
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: sudo systemctl start mysql &&  echo "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';"| sudo /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf
      - run: sudo systemctl start mysql &&  echo "FLUSH PRIVILEGES;"| sudo /usr/bin/mysql --defaults-file=/etc/mysql/debian.cnf
      - run: sudo systemctl restart mysql
      - run: composer install
      - run: composer wp-install
      - run: ./vendor/phpunit/phpunit/phpunit

  build-and-publish-artifact:
    name: Build and publish artifact
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install zip
        uses: montudor/action-zip@v1
      - name: Zip artifact
        run: cd .. && mkdir build && ls -lrth && pwd && zip -r build/simpl-checkout-plugin.zip simpl-checkout-woocommerce/*
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: simpl-checkout-plugin
            path: build/simpl-checkout-plugin.zip
