name: Build and run tests
run-name: Running feature branch workflow
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy_to_wordpress:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: upload
        env:
          SVN_USERNAME: "test"
        run: | 
          echo "!!!"
          echo "$SVN_USERNAME"
          sudo apt-get update | sudo apt install subversion
          sudo apt install ssh rsync
          /home/runner/work/simpl-checkout-woocommerce/simpl-checkout-woocommerce/scripts/sync-to-svn.sh
